Add the new Pearl installer

diff --git a/bin/pearl b/bin/pearl
--- a/bin/pearl
+++ b/bin/pearl
@@ -2,6 +2,9 @@
 
 set -e
 
+[ -z "$PEARL_ROOT" ] && { echo "Error: The variable PEARL_ROOT must be specified in order to run this script."; exit 1; }
+[ -d "$PEARL_ROOT" ] || { echo "Error: The value in variable PEARL_ROOT is not a directory."; exit 2; }
+
 NAME='Pearl'
 CMD='pearl'
 DESCRIPTION='Because only in the best shells you will find a Pearl...'
@@ -25,9 +28,10 @@ usage() {
     echo -e "Usage: $CMD <command> [args]"
 	echo
     echo -e "Commands:"
+    echo -e "  init                           Init $PEARL_HOME config directory"
     echo -e "  l[ist]                         List all the available $NAME packages"
     echo -e "  s[earch]    <pattern>          Search the available $NAME packages that match pattern"
-    echo -e "  i[nstall]   [[repo/]pkg1...]   Install $NAME or the packages if specified"
+    echo -e "  i[nstall]   [repo/]pkg1...     Install $NAME or the packages if specified"
     echo -e "  u[pdate]    [[repo/]pkg1...]   Update $NAME or the packages if specified"
     echo -e "  r[emove]    [[repo/]pkg1...]   Remove $NAME or the packages if specified"
     echo -e "  h[elp], [-h], [--help]         Show this help message"
@@ -35,7 +39,7 @@ usage() {
 }
 
 check_cli(){
-	$COMMAND_SEARCH || $COMMAND_LIST || \
+	$COMMAND_INIT || $COMMAND_SEARCH || $COMMAND_LIST || \
 			$COMMAND_INSTALL || \
 			$COMMAND_UPDATE || $COMMAND_REMOVE || \
 			$OPT_HELP || die "No command has been specified. Run: $CMD --help"
@@ -58,6 +62,7 @@ check_cli(){
 
 
 function parse_arguments(){
+    COMMAND_INIT=false
     COMMAND_LIST=false
     COMMAND_SEARCH=false
     COMMAND_INSTALL=false
@@ -69,6 +74,8 @@ function parse_arguments(){
 	for opt in "$@"
 	do
 		case "$1" in
+			init)
+				COMMAND_INIT=true; shift ;;
 			list|l)
 				COMMAND_LIST=true; shift ;;
 			search|s)
@@ -103,18 +110,11 @@ function execute_operation(){
 
 	$COMMAND_LIST && { pearl_package_list; return; }
 	$COMMAND_SEARCH && { pearl_package_list ${COMMAND_ARGS[@]}; return; }
+	$COMMAND_INIT && { pearl_init; return; }
 
 	local final_res=0
 	if $COMMAND_INSTALL; then
-		if [ -z "$COMMAND_ARGS" ]
-		then
-			if [ -z "$PEARL_ROOT" ]
-			then
-				pearl_install ${PEARL_LOCAL_ROOT}
-			else
-			    die "Pearl seems already been installed since the environment variable PEARL_ROOT is already setup."
-			fi
-		fi
+		[ -z "$COMMAND_ARGS" ] && die "No Pearl package specified."
 
 		for pkg in ${COMMAND_ARGS[@]}
 		do
