:art: Indent code for readability

diff --git a/bin/pearl b/bin/pearl
--- a/bin/pearl
+++ b/bin/pearl
@@ -24,9 +24,9 @@ KILL_CMD=kill
 ###################################
 
 usage() {
-	echo -e "$NAME ($VERSION): $DESCRIPTION"
+    echo -e "$NAME ($VERSION): $DESCRIPTION"
     echo -e "Usage: $CMD <command> [args]"
-	echo
+    echo
     echo -e "Commands:"
     echo -e "  init                           Init $PEARL_HOME config directory"
     echo -e "  l[ist]                         List all the available $NAME packages"
@@ -35,19 +35,19 @@ usage() {
     echo -e "  u[pdate]    [[repo/]pkg1...]   Update $NAME or the packages if specified"
     echo -e "  r[emove]    [[repo/]pkg1...]   Remove $NAME or the packages if specified"
     echo -e "  h[elp], [-h], [--help]         Show this help message"
-	echo
+    echo
 }
 
 check_cli(){
-	$COMMAND_INIT || $COMMAND_SEARCH || $COMMAND_LIST || \
-			$COMMAND_INSTALL || \
-			$COMMAND_UPDATE || $COMMAND_REMOVE || \
-			$OPT_HELP || die "No command has been specified. Run: $CMD --help"
+    $COMMAND_INIT || $COMMAND_SEARCH || $COMMAND_LIST || \
+	$COMMAND_INSTALL || \
+	$COMMAND_UPDATE || $COMMAND_REMOVE || \
+	$OPT_HELP || die "No command has been specified. Run: $CMD --help"
     if $OPT_HELP
     then
         if $COMMAND_SEARCH || $COMMAND_LIST || \
-			$COMMAND_INSTALL || \
-			$COMMAND_UPDATE || $COMMAND_REMOVE
+		$COMMAND_INSTALL || \
+		$COMMAND_UPDATE || $COMMAND_REMOVE
         then
             die "The help option must be used exclusively"
         fi
@@ -68,85 +68,85 @@ function parse_arguments(){
     COMMAND_INSTALL=false
     COMMAND_UPDATE=false
     COMMAND_REMOVE=false
-	COMMAND_ARGS=()
-	OPT_HELP=false
+    COMMAND_ARGS=()
+    OPT_HELP=false
 
-	for opt in "$@"
-	do
-		case "$1" in
-			init)
-				COMMAND_INIT=true; shift ;;
-			list|l)
-				COMMAND_LIST=true; shift ;;
-			search|s)
-				COMMAND_SEARCH=true; shift ; COMMAND_ARGS=("$@") ; shift ${#} ;;
-			install|i)
-				COMMAND_INSTALL=true; shift ; COMMAND_ARGS=("$@") ; shift ${#} ;;
-			update|u)
-				COMMAND_UPDATE=true; shift ; COMMAND_ARGS=("$@") ; shift ${#} ;;
-			remove|r)
-				COMMAND_REMOVE=true; shift ; COMMAND_ARGS=("$@") ; shift ${#} ;;
+    for opt in "$@"
+    do
+	case "$1" in
+	    init)
+		COMMAND_INIT=true; shift ;;
+	    list|l)
+		COMMAND_LIST=true; shift ;;
+	    search|s)
+		COMMAND_SEARCH=true; shift ; COMMAND_ARGS=("$@") ; shift ${#} ;;
+	    install|i)
+		COMMAND_INSTALL=true; shift ; COMMAND_ARGS=("$@") ; shift ${#} ;;
+	    update|u)
+		COMMAND_UPDATE=true; shift ; COMMAND_ARGS=("$@") ; shift ${#} ;;
+	    remove|r)
+		COMMAND_REMOVE=true; shift ; COMMAND_ARGS=("$@") ; shift ${#} ;;
 
-			help|h|-h|--help) OPT_HELP=true ; shift ;;
+	    help|h|-h|--help) OPT_HELP=true ; shift ;;
 
-			--) shift ; break ;;
-			-*) die "Invalid option $1" ;;
-			*) break ;;
-		esac
-	done
+	    --) shift ; break ;;
+	    -*) die "Invalid option $1" ;;
+	    *) break ;;
+	esac
+    done
 
-	ARGS=()
-	for arg in "$@"
-	do
-		ARGS+=("$arg")
-	done
+    ARGS=()
+    for arg in "$@"
+    do
+	ARGS+=("$arg")
+    done
 }
 
 function execute_operation(){
-	$OPT_HELP && usage && return
-	$COMMAND_INIT && { pearl_init; pearl_load_repos; return; }
+    $OPT_HELP && usage && return
+    $COMMAND_INIT && { pearl_init; pearl_load_repos; return; }
 
     # Ensure to load the repos at least once
     pearl_load_repos
 
-	$COMMAND_LIST && { pearl_package_list; return; }
-	$COMMAND_SEARCH && { pearl_package_list ${COMMAND_ARGS[@]}; return; }
+    $COMMAND_LIST && { pearl_package_list; return; }
+    $COMMAND_SEARCH && { pearl_package_list ${COMMAND_ARGS[@]}; return; }
 
-	local final_res=0
-	if $COMMAND_INSTALL; then
-		[ -z "$COMMAND_ARGS" ] && die "No Pearl package specified."
+    local final_res=0
+    if $COMMAND_INSTALL; then
+	[ -z "$COMMAND_ARGS" ] && die "No Pearl package specified."
 
-		for pkg in ${COMMAND_ARGS[@]}
-		do
-		    pearl_package_install "$pkg" || final_res=$?
-		done
-	    source_pearl
-	elif $COMMAND_UPDATE; then
-		[ -z "$COMMAND_ARGS" ] && pearl_update
+	for pkg in ${COMMAND_ARGS[@]}
+	do
+	    pearl_package_install "$pkg" || final_res=$?
+	done
+	source_pearl
+    elif $COMMAND_UPDATE; then
+	[ -z "$COMMAND_ARGS" ] && pearl_update
 
-		for pkg in ${COMMAND_ARGS[@]}
-		do
-		    pearl_package_update "$pkg" || final_res=$?
-		done
-	    source_pearl
-	elif $COMMAND_REMOVE; then
-		# Do not send a signal if $NAME has been removed
-		[ -z "$COMMAND_ARGS" ] && pearl_remove && return 0
+	for pkg in ${COMMAND_ARGS[@]}
+	do
+	    pearl_package_update "$pkg" || final_res=$?
+	done
+	source_pearl
+    elif $COMMAND_REMOVE; then
+	# Do not send a signal if $NAME has been removed
+	[ -z "$COMMAND_ARGS" ] && pearl_remove && return 0
 
-		for pkg in ${COMMAND_ARGS[@]}
-		do
-		    pearl_package_remove "$pkg" || final_res=$?
-		done
-	    source_pearl
-	fi
+	for pkg in ${COMMAND_ARGS[@]}
+	do
+	    pearl_package_remove "$pkg" || final_res=$?
+	done
+	source_pearl
+    fi
 
-	return $final_res
+    return $final_res
 }
 
 function source_pearl(){
-	# Send signal to parent in order to (re)source pearl
+    # Send signal to parent in order to (re)source pearl
     [ -z "$PEARL_ROOT" ] || $KILL_CMD -USR1 $PPID
-	return 0
+    return 0
 }
 
 parse_arguments "$@"
